apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx

namespace: ingress-nginx

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    version: 4.12.0 # 4.12.0 as at 20250205 Chart version: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    valuesFile: ./values.yaml

resources:
  - ./resources/namespace.yaml

