controller:
  config:
    enable-real-ip: true
  publishService:
    enabled: true
  service:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "10.20.26.10"
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
    loadBalancerSourceRanges:
      - 10.10.0.0/16
      - 10.20.0.0/16
      - 10.0.0.0/8 # need this to be able to connect between clusters
  ingressClassResource:
    default: true

