apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: bitwarden-ca-bundle
  namespace: external-secrets
spec:
  sources:
    - useDefaultCAs: false  # Avoid using system default CAs
    - secret:
        name: bitwarden-tls-certs
        key: ca.crt  # Extracts the CA from this secret
  # target:
  #   configMap:
  #     key: caBundle
  target:
    configMap:
      name: bitwarden-ca-configmap
      key: caBundle  # The key inside the secret
    namespaceSelector:
      matchLabels:
        linkerd.io/inject: "enabled"