apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-cd-application-sets

namespace: argocd

resources:
  - ./resources/application-set-crds.yaml
  - ./resources/application-set-core.yaml
  - ./resources/root.yaml
  - ./resources/root-private.yaml # apps setup not in public github
  # - ./resources/application-set-apps.yaml
