apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # application.resourceTrackingMethod: annotation
  # admin.enabled: 'false'
  # statusbadge.enabled: 'true'
  # users.anonymous.enabled: 'true'
  # ga.trackingid: 'UA-105170809-6'
  url: https://argo-cd.rockyroad.rocks
  exec.enabled: "true"
  kustomize.buildOptions: --enable-helm
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
      - MetalLB
      - controller #metallb
      - external-secrets
      - metallb-controller
  resource.customizations.ignoreDifferences: |
    v1/Secret:
      name: external-secrets-webhook
      jqPathExpressions:
        - .data
  accounts.homepagereadonly: apiKey # Added to create a 'homepagereadonly' user to give gethomepage access

  oidc.config: |
    name: Rockyroad
    issuer: https://keycloak.rockyroad.rocks/realms/rockyroadrocks
    clientID: argocd
    clientSecret: $argocd-oidc-secret:argocd-oidc-secret # format of this is documented here: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets
    requestedScopes: ["openid", "profile", "email", "groups"]

  # configManagementPlugins: |
  #   - name: flux
  #     generate:
  #       command: [sh, -c]
  #       args: ["argocd-flux-plugin . --path $GIT_PATH"]
  # dex.config: |
  #   connectors:
  #   - type: github
  #     id: github
  #     name: GitHub
  #     config:
  #       clientID: fb563b3a8dd7ea52f683
  #       clientSecret: $argocd-auth:dex.github.clientSecret
  #       orgs:
  #       - name: argoproj
  #         teams:
  #         - argo-rollouts-approvers
  #         - argo-workflows-approvers
  #         - argocd-approvers