apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:admin, applications, exec, *, allow
    g, readonly, role:readonly
  policy.default: role:readonly
  scopes: '[groups, email]'