apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.overlay.csv: |
    p, role:admin, exec, create, */*, allow
    g, homepagereadonly, role:readonly
    g, argocd-admins, role:admin
  # Added to create a 'homepagereadonly' user to give gethomepage access
  policy.default: role:admin