apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-load-balancer-ip-pool
spec:
  blocks:
    - cidr: 10.20.26.0/26 # start: "10.20.26.0"  stop: "10.20.26.63"
    # - cidr: 10.20.26.0/27 # start: "10.20.26.0"  stop: "10.20.26.31"
    # - cidr: 10.20.26.32/27 # start: "10.20.26.32"  stop: "10.20.26.63"
    # - cidr: 10.20.10.10/32 # specifically for adguardhome
    # - start: "10.20.26.32"
    #   stop: "10.20.26.63"
  disabled: false


# COMMAND TO RUN TO SEE ALL THE ADDRESSES ALLOCATED BY CILIUM 
# kubectl get svc -A -o jsonpath='{range .items[?(@.status.loadBalancer.ingress)]}{.metadata.namespace}{"\t"}{.metadata.name}{"\t"}{.status.loadBalancer.ingress[*].ip}{"\n"}{end}'
