apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: cilium-gateway
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    # group: cilium.io
    kind: ConfigMap
    group: ""
    name: cilium-gateway-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-gateway-config
spec:
  loadBalancer:
    ip: 10.20.26.14