apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  # Optional: Select specific nodes to perform announcements
  # nodeSelector:
  #   matchLabels:
  #     kubernetes.io/hostname: node-1