apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium

namespace: kube-system

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    releaseName: cilium
    namespace: kube-system
    version: 1.18.2 # make sure you update the CRDs in the separate file at the same time
    valuesFile: ./values.yaml

resources:
  - ./resources/cilium-l2-announcement-policy.yaml
  - ./resources/cilium-load-balancer-ip-pool.yaml
