apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: talos-backup

namespace: talos

resources:
  - ./resources/namespace.yaml
  - ./resources/talos-backup-secrets.yaml
  - ./resources/talos-backup-cronjob.yaml

