apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # This does not contain _all_ core directories. Just what's needed to
  # get argo cd setup and running everything itself.
  - ./cert-manager/cert-manager
  # - ./cert-manager/trust-manager
  - ./external-secrets/bitwarden-sdk-certificate-issuer
  - ./external-secrets/external-secrets-operator
  - ./metallb-system/metallb
  - ./kube-system/nfs-subdir-external-provisioner
  - ./ingress-nginx/ingress-nginx
  # - ./kube-system/cilium
  - ./argocd/argocd
  - ./argocd/application-sets
  - ./argocd/root\argo-cd-root.yaml
  # - ./rook-ceph/rook-ceph
  # - ./velero/velero
