apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # This does not contain _all_ core directories. Just what's needed to
  # get argo cd setup and running everything itself.
  - ./cert-manager/cert-manager
  # - ./cert-manager/trust-manager
  - ./external-secrets/bitwarden-sdk-certificate-issuer
  - ./external-secrets/external-secrets-operator
  # - ./external-secrets/bitwarden-sdk-server
  - ./metallb/metallb
  - ./nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
  # - ./bitwarden/sm-operator
  # - ./kube-system/cilium
  # - ./argocd/argo-cd
  # - ./argocd/application-sets
  # - ./rook-ceph/rook-ceph
  # - ./velero/velero
