
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-externalsecrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd # required as per doco: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#alternative
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: argocd-oidc-secret # The name of the Kubernetes Secret to be created.
    creationPolicy: Owner
  data:
    - secretKey: argocd-oidc-secret
      remoteRef:
        key: "5e5f8547-0df6-4976-9672-b3df002469db"



# need to rewrite dns for this to work: 
# keycloak.rockyroad.rocks keycloak-service.keycloak.svc.cluster.local