apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  # target:
  #   creationPolicy: Owner
  #   template:
  #     type: Opaque
  #     engineVersion: v2
  #     data:
  #       api-token: "{{ .api_token }}"
  data:
    - secretKey: api-token
      remoteRef:
        key: "96979ab9-057c-40bb-99ca-b27c01633dc6"
