apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-externalsecrets
  # namespace: NOTREQUIREDINSIDECHART
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: keycloak-postgres-externalsecrets
    template:
      data:
        keycloak-postgres-secret: '{{ .POSTGRES_PASSWORD }}'
        keycloak-postgres-url: 'postgresql://keycloak-user:{{ .POSTGRES_PASSWORD }}@postgres-service/keycloak'
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "05147819-db38-468c-a0fd-b3da017e00e3"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-externalsecrets
  # namespace: NOTREQUIREDINSIDECHART
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: keycloak-externalsecrets
    # template:
    #   data:
    #     keycloak-postgres-secret: '{{ .KEYCLOAK_PASSWORD }}'
  data:
    - secretKey:  admin
      remoteRef:
        key: "33322abf-63da-4a06-8018-b3da018381d9"
    - secretKey:  password
      remoteRef:
        key: "c04bf67e-0e3f-4626-8cee-b3da0182ced5"
