apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-externalsecrets
  # namespace: NOTREQUIREDINSIDECHART
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: keycloak-externalsecrets
    template:
      data:
        keycloak-postgres-secret: '{{ .POSTGRES_PASSWORD }}'
        keycloak-postgres-url: 'postgresql://keycloak-user:{{ .POSTGRES_PASSWORD }}@postgres-service/keycloak'
  data:
    # - secretKey: keycloak-backup-token
    #   remoteRef:
    #     key: ""
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "05147819-db38-468c-a0fd-b3da017e00e3"
