apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: node-feature-discovery

namespace: node-feature-discovery

helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    releaseName: node-feature-discovery
    version: v0.17.1 # v0.17.1 as at 20250215 https://github.com/kubernetes-sigs/node-feature-discovery
    valuesFile: ./values.yaml

resources:
  - ./resources/namespace.yaml
