apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets-operator

namespace: external-secrets

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    namespace: external-secrets
    version: 0.14.0 # 0.14.0 as at 20250207 # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
    valuesFile: values.yaml

resources:
  - ./resources/namespace.yaml
  - ./resources/bitwarden-cluster-certificate-issuer.yaml
  - ./resources/bitwarden-certificate.yaml
  # - ./resources/bitwarden-certificate-bundle.yaml
  - ./resources/cluster-secret-store.yaml
