apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: talos-backup-secrets
  namespace: talos
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  # target:
  #   creationPolicy: Owner
  #   template:
  #     type: Opaque
  #     engineVersion: v2
  #     data:
  #       api-token: "{{ .api_token }}"
  data:
    - secretKey: access-key-id
      remoteRef:
        key: "b1519077-10be-4257-8d09-b27e0181e6cc"
    - secretKey: secret-access-key
      remoteRef:
        key: "162e82c2-db32-468c-a87a-b27e0181cdeb"
    - secretKey: endpoint
      remoteRef:
        key: "49f60a48-9e17-4c01-80a2-b27e01816e77"
    - secretKey: age-public-key
      remoteRef:
        key: "98fbd92c-b572-4100-9fc5-b27e01814f6d"
