apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nominatim-externalsecrets
  # namespace: NOTREQUIREDINSIDECHART
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
    - secretKey: nominatim-postgres-secret
      remoteRef:
        key: "50a0cbd8-b61b-4a16-8f6c-b37d0049168c"
