# https://gethomepage.dev/installation/k8s/
# https://gethomepage.dev/installation/k8s/#deployment

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # name: talos-gpu
    server: https://kubernetes.default.svc
    namespace: homepage
  project: default
  source:
  #   chart: homepage
  #   repoURL: https://jameswynn.github.io/helm-charts
  #   targetRevision: 0.9.0 # 0.9.0 as at 20250102
  #   helm:
  #     values: |
    path: cluster/apps/charts/homepage
    repoURL: https://github.com/ugoogalizer/kubernetes-talos.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
