# https://konpyutaika.github.io/nifikop/docs/2_deploy_nifikop/2_customizable_install_with_helm

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifikop
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # name: talos-gpu
    server: https://kubernetes.default.svc
    namespace: nifikop
  project: default
  source:
    chart: nifikop
    repoURL: oci://ghcr.io/konpyutaika/helm-charts
    targetRevision: 1.12.0 # 1.12.0 as at 20250224 https://github.com/orgs/konpyutaika/packages?repo_name=helm-charts
    # Also installs a whole bunch of CRDs into the cluster
    helm:
      values: |
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

