# https://artifacthub.io/packages/helm/ollama-helm/ollama/0.4.0

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # name: talos-gpu
    server: https://kubernetes.default.svc
    namespace: ollama
  project: default
  source:
    chart: ollama
    repoURL: https://otwld.github.io/ollama-helm/
    targetRevision: 1.5.0 # 1.5.0 as at 20250102
    helm:
      values: |
        runtimeClassName: "nvidia" # Required to make the nvidia drivers available
        ollama:
          gpu:
            # -- Enable GPU integration
            enabled: true
            # -- GPU type: 'nvidia' or 'amd'
            type: 'nvidia'
            # -- Specify the number of GPU to 1
            number: 1
        ingress:
          enabled: true
          hosts:
          - host: ollama.rockyroad.rocks
            paths:
              - path: /
                pathType: Prefix
          tls:
            - hosts:
              - ollama.rockyroad.rocks
              secretName: ollama-tls   
        persistentVolume:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

