# https://artifacthub.io/packages/helm/ollama-helm/ollama/0.4.0

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # name: talos-gpu
    server: https://kubernetes.default.svc
    namespace: ollama
  project: default
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com/
    targetRevision: 5.13.0 # 5.13.0 as at 20250216
    helm:
      values: |
        ollama:
          enabled: true

          runtimeClassName: "nvidia" # Required to make the nvidia drivers available
          ollama:
            gpu:
              # -- Enable GPU integration
              enabled: true
              # -- GPU type: 'nvidia' or 'amd'
              type: 'nvidia'
              # -- Specify the number of GPU to 1
              number: 1
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-dns01-prod"
              kubernetes.io/ingress.class: "nginx"
            hosts:
            - host: ollama.rockyroad.rocks
              paths:
                - path: /
                  pathType: Prefix
            tls:
              - hosts:
                - ollama.rockyroad.rocks
                secretName: ollama-tls   
          persistentVolume:
            enabled: true
        pipelines:
          enabled: true
        tika:
          enabled: true
        ingress:
          enabled: true
          class: "nginx"
          host: open-webui.rockyroad.rocks
          tls: true
          # annotations:
          #   cert-manager.io/cluster-issuer: "letsencrypt-dns01-prod"
          #   # kubernetes.io/ingress.class: "nginx"
          # hosts:
          # - host: open-webui.rockyroad.rocks
          #   paths:
          #     - path: /
          #       pathType: Prefix
          # tls:
          #   - hosts:
          #     - open-webui.rockyroad.rocks
          #     secretName: open-webui-tls   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

