apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # name: talos-gpu
    server: https://kubernetes.default.svc
    namespace: osm
  project: default
  source:
    path: cluster/apps/charts/osm
    repoURL: https://github.com/ugoogalizer/kubernetes-talos.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
