apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-externalsecrets
  # namespace: NOTREQUIREDINSIDECHART
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
    - secretKey: talos-externaldns-rockyroad
      remoteRef:
        key: "6a0c480b-e0b8-4d43-9c79-b44500a4da38"

# kubectl create namespace terraria
# kubectl config set-context --current --namespace=terraria
# kubectl create secret generic terraria-creds --from-literal=username='XXX' --from-literal=password='XXX'
# kubectl create secret generic rcon-creds --from-literal=password='XXX'

# # To get the username and password use: 
# kubectl get secret terraria-creds -o jsonpath="{.data.username}" | base64 -d
# kubectl get secret terraria-creds -o jsonpath="{.data.password}" | base64 -d
# kubectl get secret rcon-creds -o jsonpath="{.data.password}" | base64 -d
